### ISSUE TITLE
request the "fixing" of small inconsistencies

### ISSUE THREAD

**Issue by pitsianis** [LiorSinai/TransformersLite.jl#1]
Thank you so much for this work, it is very inspiring. 
I am writing to request the "fixing" of some small inconsistencies.

 * Fix the way the Amazon data are downloaded, 
 * Fix the location the Amazon data  are saved and use the location in the example scripts
 * Parse the data as saved (for example as JSON format)
 * use packages like BytePairEncoding that are registered

... so that the examples run without the need to be modified by the user.

**Comment by LiorSinai** [comment]
With regards to these action points:
- I've added a Python script for doing this. A pure Julia way is ideal but I like the HuggingFace implementation which converts the array of JSONs to the more efficient and compact Arrow format.
- The path is now set in the Python script.
- See the first point.
- I've decided not to link to this particular package because I will have to change files to suit its API and its documentation at the moment is poor. However in the interest of making this repo more independent of TokenisersLite I am setting the default to no tokeniser - that works well enough for this toy problem.
Thank you for raising this issue and giving me a reason to revisit old code.
